// config.js
// Supabase Configuration
const SUPABASE_CONFIG = {
  url: 'https://talqdxageqbvsavscyqt.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbHFkeGFnZXFidnNhdnNjeXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mjc0OTAsImV4cCI6MjA1ODMwMzQ5MH0.YBMSv0YClLrGSM16M5-GXNefh-5MbPQwjh-CBET0shU',
  serviceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbHFkeGFnZXFidnNhdnNjeXF0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjcyNzQ5MCwiZXhwIjoyMDU4MzAzNDkwfQ.O9eyG9xhAfD0AQARv-reR2CnTvf2TSsyRGxvbirlpko'
};
