// Supabase Configuration
const SUPABASE_CONFIG = {
  url: "https://kstfouovkbnadirodpio.supabase.co",
  anonKey:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdGZvdW92a2JuYWRpcm9kcGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTU3MDUsImV4cCI6MjA1NzY5MTcwNX0._ywN27wvbd0NB35hGdANnmgtJ9II1YBy2MRyco5dm9g",
  serviceRoleKey:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdGZvdW92a2JuYWRpcm9kcGlvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjExNTcwNSwiZXhwIjoyMDU3NjkxNzA1fQ.za0xWl7pcEijfYZ7r2VowLxUerHW84sOtQCIHM_8x_4",
}

